name: Main Workflow
on:
  push:
    branches:
      - "main"
permissions:
  contents: write
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --debug --no-shrink --split-per-abi
      - uses: actions/upload-artifact@v2
        with:
          name: build-android
          path: build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk
          retention-days: 1
  publish-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter analyze
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /flora_test/
